x-logging:
  &default-logging
  driver: journald

x-labels:
  &default-labels
  org.supernetworks.ci: ${CI:-false}
  org.supernetworks.version: ${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}

services:
  spr_vaultwarden:
    container_name: spr_vaultwarden
    image: vaultwarden/server:latest
    network_mode: ${NETWORK_MODE:-host}
    environment:
      ROCKET_PORT: "8989"
    build:
      context: .
      labels: *default-labels
    logging: *default-logging
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "${SUPERDIR}./state/plugins/vaultwarden/:/state/plugins/vaultwarden/"
      - "${SUPERDIR}./state/public/:/state/public/:ro"
      - "${SUPERDIR}./configs/vaultwarden/data/:/data"

#      - "${SUPERDIR}./state/api/:/state/api/:ro" #uncomment me for SPRBUS access
